[package]
name = "multimodars"
version = "0.1.1"
edition = "2021"
license = "MIT"

[lib]
name = "multimodars"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
csv = "1.1"
serde = { version = "1.0.219", features = ["derive"]}
image = "0.25.5"
nalgebra = "0.34.0"
toml = "0.9.5"
rayon = "1.7.1"
crossbeam = "0.8.4"
anyhow = "1.0.97"
approx = "0.5"
stl_io = "0.8.5"